### ISSUE TITLE
安装执行后，报告html中显示乱码

### ISSUE THREAD

**Issue by bs111** [lgxqf/UICrawler#3]
应该是gb2312,但是报告中申明是utf-8

**Comment by quxiaozha** [comment]
有两种解决方案：
1. 判断为windows下运行时，将相关的编码都改成gbk；
2. 将编码统一成utf-8，在cmd运行时，使用```java -Dfile.encoding=UTF-8 -jar .\UICrawler-2.0.jar```指定编码。

存在问题：
1. 方案1中存在的问题是，在windows中用eclipse或者idea通过源码执行时，由于默认为utf-8编码，所以会出现乱码，解决办法是添加-Dfile.encoding=GBK
2. 方案2的问题是，由于cmd下默认为gbk编码，所以运行时cmd窗口中打印的日志会乱码，但是日志文件和报告文件不会乱码。

综上，为方便直接通过cmd执行的同学，故采用方案1，如果需要windows下使用eclipse或idea调试执行的同学建议加上```VM Options:-Dfile.encoding=GBK```以解决乱码问题。
