### ISSUE TITLE
PLATFORM_VERSION 在代码中指定会导致异常

### ISSUE THREAD

**Issue by wangzi1325** [lgxqf/UICrawler#4]
PLATFORM_VERSION 在代码中指定会导致异常
![image](https://user-images.githubusercontent.com/4196935/44500589-e243f600-a6bb-11e8-9d63-f5ac09da41e8.png)

目前看来会导致 webdriveragent无法正常加载

**Comment by wangzi1325** [comment]
#5

**Comment by lgxqf** [comment]
恩 我会改成 用ideviceinfo取product version

**Comment by wangzi1325** [comment]
这个不需要吧，去掉就行了

**Comment by lgxqf** [comment]
removed.
