### ISSUE TITLE
判断点击后是否同一页面有点问题

### ISSUE THREAD

**Issue by yxgtianya** [lgxqf/UICrawler#7]
isSamePage(previousPageStructure,afterPageStructure)这个方法在启动时候点击权限弹窗时判断有点问题，多个权限点击允许前后pageStructure是一样的

**Comment by lgxqf** [comment]
pageStructure确实是一样的 这个可以能过白名单解决  

  ITEM_WHITE_LIST:
  - 确定
  - 允许
