### ISSUE TITLE
是否支持多台机器同时执行，如何修改文件？

### ISSUE THREAD

**Issue by songjinhua** [lgxqf/UICrawler#9]
多台手机一起执行

**Comment by lgxqf** [comment]
一个jar只支持运行一个手机，  多个手机时每个手机需运行单独的jar

**Comment by songjinhua** [comment]
> 一个jar只支持运行一个手机， 多个手机时每个手机需运行单独的jar

直接配置文件里写两个机型，然后执行的时候启2个dos窗口直接单独指定机型跑吗？appium需要启两个吗？

**Comment by lgxqf** [comment]
对 appium的个数与手机的个数一样
